version: '3'
services:
  server:
    build: .
    command: $COMMAND
    ports:
    - $server_port
    - $redis_port
    depends_on:
    - redis
  redis:
    image: redis:3.2.0
    ports:
      - "6379:6379"
  

